config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root to: 'posts#index'
  
  resources :posts do
    collection do 
      post :confirm
    end
    
    member do
      post :edit_confirm
    end
  end
  
  resources :users, only: [:new, :create, :show] do
    member do
      get :favorites
    end
   end
   
  resources :profile
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]
 
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
     validates :content,length: { in: 1..140 }
     mount_uploader :image, ImageUploader
     belongs_to :user
     has_many :favorites, dependent: :destroy
end

app/models/profile.rb
class Profile < ApplicationRecord
   mount_uploader :profilepic, ProfilepicUploader
   belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
  has_many :posts
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  has_one  :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  add_flash_types :success, :info, :warning, :danger
  before_action :require_login
  
  private
  
  def require_login
    unless logged_in?
      flash[:danger] = "アクセスするためにはログインしてください"
      redirect_to new_session_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
 
  def create
    favorite = current_user.favorites.create(post_id: params[:post_id])
    redirect_to posts_url, success: "#{favorite.post.user.name}さんの写真をお気に入りに登録しました"
  end
  
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to posts_url, success: "#{favorite.post.user.name}さんの写真をお気に入りを解除しました"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   before_action :set_post,only: [:destroy, :update]
   before_action :correct_user?,only: [:edit]

   def index
     @posts = Post.all
   end
    
   def new
     if params[:back] 
       @post = Post.new(post_params)
     else
       @post = Post.new
     end
   end
    
   def confirm
     @post = current_user.posts.build(post_params)
       if @post.invalid?
         render 'new'
       end
   end
    
   def create
     @post = current_user.posts.build(post_params)
       if @post.save
         redirect_to posts_path, success:"投稿しました"
         ConfirmMailer.confirm_mail(@post).deliver
       else
         render 'confirm'
       end
   end
    
   def edit
     if params[:back]
       @post = Post.new(post_params)
       @post.image = params[:image_cache]
     else
       @post = Post.find(params[:id])
     end
   end
   
   def edit_confirm
      @post = current_user.posts.build(post_params)
      if @post.invalid?
          render 'new'
      end
   end
   
   def update
    if @post.update(post_params)
      redirect_to posts_path, success:"編集しました！"
    else
      render 'edit'
    end
   end
    
   def destroy
     @post.destroy
     redirect_to posts_path, success:"削除しました"
   end
    
   def show
     @favorite = current_user.favorites.find_by(post_id: @post.id)
   end
    
private
    
   def post_params
     params.require(:post).permit(:content, :image,:image_cache)
   end
    
   def set_post
     @post = Post.find(params[:id])
   end
    
   def correct_user?
     @selected_post = Post.find(params[:id])
     @user = User.find_by(id: @selected_post.user_id)
     unless @user == current_user
       flash[:danger] = "アクセスする権限がありません。正しいユーザーでログインしてください"
       redirect_to root_url
     end
   end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def new
  @profile = Profile.new
  # @profile = current_user.profile.new(user_id: current_user.id)
  end
  
  def create
   @profile = Profile.new(profile_params)
  # @profile.user_id = current_user.id
  @profile = @profile.save
  redirect_to user_path(current_user.id)
  end
  
  def edit
    @profile= Profile.find(current_user.profile.id)
  end
  
  def update
    @profile= Profile.find(current_user.profile.id)
    @profile.update(profile_params)
    redirect_to user_path, notice:"編集しました！"
  end
  
  def show
    @user = User.find(params[:id])
    @profile= Profile.find_by(user_id: params[:id])
  end
  
  private
  
  def profile_params
    params.require(:profile).permit(:profilepic, :introduction,:profilepic_cache, :birthday)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  
  def new
  end
  
  def create
    user = User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:success] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  
  def new
   @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
       render 'new' 
    end
  end
  
  def show
    @user = User.find(params[:id])
    @profile = current_user.profile
  end

  def favorites
    @user = User.find(params[:id])
    @favorites = current_user.favorite_posts
  end
  
  
  private
  
  def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExamIgm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    
    <% flash.each do |name, msg| %>
　　　<%= content_tag :div, msg, class: "alert alert-#{name}" %>
　　<% end %>
　　
    <%= notice %>
    
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
             <span class="sr-only">メニュー</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
          <%= link_to 'IGM', posts_path, class: "navbar-brand" %>
        </div>
        
        <div id="gnavi" class="collapse navbar-collapse">
    <ul class="nav navbar-nav  navbar-left">
      <li><%= link_to '新規投稿', new_post_path %></li>
    </ul>
    <ul class="nav navbar-nav  navbar-right">
     <% if logged_in? %>
       <li><%= link_to "Profile", user_path(current_user.id) %></li>
       <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
     <% else %>
       <li><%= link_to "Sign up", new_user_path %></li>
       <li><%= link_to "Login", new_session_path %></li>
     <% end %>
    </ul>
  </div>
</nav>
      <%= yield %>
   </div>
  </body>
</html>

app/views/posts/_errormsg.html.erb
 <% if @post.errors.any? %>
        <div id="error_explanation">
            <h2><%= @post.errors.count %>件のエラーがあります</h2>
            <ul>
            <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>

app/views/posts/confirm.html.erb
<h1>以下の内容で投稿する</h1>


<%= form_with(model: @post, url:posts_path, local: true, method: :post ) do |form| %>

  <%= form.label :content %>
  <%= form.hidden_field :content %>
  
  <% if @post.image.url.present? %>
    <%= image_tag(@post.image.url) %>
  <% end %>
  <%= form.hidden_field :image_cache %>
  
  <p><%= @post.content %></p>
  <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model: @post, url: new_post_path, local: true,method: :get) do |form| %>
    <%= form.hidden_field :content %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/posts/edit.html.erb
<h1>home</h1>

<%= form_with(model: @post, url: edit_confirm_post_path, local: true, method: :post) do |form| %>
  <%= render 'errormsg' %>
  <%= form.label :content %>
  <%= form.text_field :content %>
  
  <%= form.label :image %>
  <%= image_tag(@post.image.url) if @post.image.url %>
  <%= form.file_field :image %>
  <%= form.submit %>
<% end %>

app/views/posts/edit_confirm.html.erb
<h1>以下の内容で編集する</h1>


<%= form_with(model: @post, url:post_path, local: true, method: :put ) do |form| %>

  <%= form.label :content %>
  <%= form.hidden_field :content %>
  <p><%= @post.content %></p>
  
  <% if @post.image.url.present? %>
    <%= image_tag(@post.image.url) %>
  <% end %>
  <%= form.hidden_field :image_cache %>
  
  <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model: @post, url: edit_post_path, local: true, method: :get) do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/posts/index.html.erb
<h1>home</h1>
  <% if current_user.present? %>
    <div class="jumbotron">
      <h1>画像とテキストを投稿しよう！</h1>
      <p>IGMは画像とテキストを投稿できるサイトです。</p>
      <% if logged_in? %>
        <p><%= link_to 'いますぐ投稿！', new_post_path, class:"btn btn-primary btn-lg" %></p>
      <% else %>
        <p><%= link_to 'アカウントを作る', new_user_path, class:"btn btn-primary btn-lg" %></p>
      <% end %>
    </div>
  
   <div class="row">
     <% @posts.each do |post| %>
     <div class="col-sm-6 col-md-4">
       <div class="thumbnail">
         <% if post.image.url.present? %>
           <%= image_tag(post.image.url) %>
         <% end %>
      <div class="caption">
        <p>テキスト:<%= post.content %></p>
        <p>投稿者<%= link_to "#{post.user.name}", profile_path(post.user_id), method: :get %></p>
        <% if post.user_id != current_user.id %>
          <% if current_user.favorites.find_by(post_id: post.id).present? %>
            <p><%= link_to 'お気に入り解除する', favorite_path(current_user.favorites.find_by(post_id: post.id)), method: :delete, class: 'btn btn-danger' %></p>
          <% else %>
            <p><%= link_to 'お気に入りする', favorites_path(post_id: post.id), method: :post, class: 'btn btn-primary' %></p>
          <% end %>
        <% end %>
     
        <% if post.user.id == current_user.id %>
          <p><%= link_to '編集する', edit_post_path(post.id), method: :get %></p>
          <p><%= link_to '削除する', post_path(post.id), method: :delete, data: {confirm: '本当に削除していいですか？'} %></p>
        <% end %>
      </div>
     </div>
    </div>
   <% end %>
  </div>
  <% else %>
    <p>見るにはログインしてください</p>
  <% end %>

app/views/posts/new.html.erb
<h1>home</h1>

<%= form_with(model: @post, url: confirm_posts_path, local: true, method: :post) do |form| %>
<%= render 'errormsg' %>
<%= form.label :content %>
<%= form.text_field :content %>

<%= form.label :image %>
<%= image_tag(@post.image.url) if @post.image.url %>
<%= form.file_field :image %>


<%= form.submit %>
<% end %>

app/views/users/_errormsg.html.erb
 <% if @user.errors.any? %>
        <div id="error_explanation">
            <h2><%= @user.errors.count %>件のエラーがあります</h2>
            <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
            </ul>
        </div>
    <% end %>

app/views/users/favorites.html.erb
<h1><%= @user.name %></h1>

<h1>お気に入り投稿一覧</h1>
 <% @favorites.each do |favorite| %>
    <tr>
      <td> <%= favorite.content %></td>
      <% if favorite.image.url.present? %>
        <td><%= image_tag(favorite.image.url) %></td>
      <% end %>
      <td>　　投稿者：<%= favorite.user.name  %></td>
    </tr>
<% end %>

 <p><%= link_to 'ホームに戻る', posts_path, class:"btn btn-primary btn-lg" %></p>

app/views/users/new.html.erb
<h1>Sign in</h1>

<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'errormsg' %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.label :email %>
  <%= f.text_field :email %>
  
  <%= f.label :password %>
  <%= f.password_field :password %>
  
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  
  <%= f.submit "アカウント登録" %>

<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p>メールアドレス:<%= @user.email %></p>

<%= link_to 'お気に入り写真一覧', favorites_user_path(@user.id), method: :get, class: 'btn btn-danger' %><br>
  <% if current_user.profile.present? %>
    <%= @profile.introduction %><br>
    <%= @profile.birthday %><br>
    <% if @profile.profilepic.url.present? %>
      <%= image_tag(@profile.profilepic.url) %><br>
    <% end %>
    
    <%= link_to 'プロフィール編集', edit_profile_path, method: :get, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'プロフィール作成', new_profile_path, method: :get, class: 'btn btn-danger' %>
  <% end %>
 <p><%= link_to 'ホームに戻る', posts_path, class:"btn btn-primary btn-lg" %></p>